services:
  - type: web
    name: studentmove-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: studentmove-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: studentmove-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: studentmove-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: studentmove-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: studentmove-db
          property: password
      - key: MAIL_MAILER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

  - type: pserv
    name: studentmove-db
    env: mysql
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: studentmove_db
      - key: MYSQL_USER
        value: studentmove_user
      - key: MYSQL_PASSWORD
        generateValue: true

